<a href="https://colab.research.google.com/github/greek-nlp/benchmark/blob/main/air_gr_nlp_benchmark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Greek NLP AIR Benchmark

```
Based on this Greek NLP Systematic Survey:
https://www.cell.com/patterns/fulltext/S2666-3899(25)00161-8

```

## Data loading

In [1]:
%%capture
!git clone https://github.com/greek-nlp/gen-a.git
!pip install zenodo-get
!pip install wget
!pip install datasets
!pip install conll-df

In [2]:
import pandas as pd
import importlib

gr_data = pd.read_csv('gen-a/data.csv')
gena = importlib.import_module("gen-a.data_wrapper")

## Task: Toxicity

In [ ]:
toxicity = gena.ZampieriDt(datasets = gr_data)
toxicity_train = toxicity.get('train')

In [ ]:
toxicity_train.sample()

        id                                              tweet subtask_a
8264  5006  Όλοι περιμένουμε την φωτογράφηση με τα κοτόπου...       NOT

## Task: Gramatical Error Detection/Correction

In [ ]:
gec = gena.KorreDt(datasets=gr_data)
gec_test = gec.get('test')

Download github items in directory: /content/repo_244
Successfully downloaded GNC

In [ ]:
gec_test.sample()

,original_text,corrected_text,label_annA,error_description_annA,error_type_annA,fluency_annA,label_annB,error_description_annB,error_type_annB,fluency_annB
152,Ακομα πρέπει να τιμούν τους αγώνες των μεγάλων...,Ακόμα πρέπει να τιμούν τους αγώνες των μεγάλων...,e,M,ACC,5.0,e,M,ACC,5.0

## Task: Machine Translation

In [ ]:
mt = gena.ProkopidisMtDt(datasets=gr_data)
pd.set_option('display.max_colwidth', None)
for lang in mt.target_langs:
  print(f"Language: {lang} ({mt.langs_dict[lang]})")
  display(mt.get(lang, 'train').sample())

source: ell, target: eng
source: ell, target: jpn
source: ell, target: fas
Language: eng (English)

,source,target
25119,Το σχέδιο περιλαμβάνει μείωση στις επιδοτήσεις καυσίμων -με άμεση επίπτωση στις τιμές βασικών αγαθών- και σημαντικές περικοπές στις κρατικές δαπάνες.,[The plan included a reduction in fuel subsidies - which has a direct effect on the prices of basic commodities - and significant cuts to government spending.]

Language: jpn (Japanese)

,source,target
6045,"Διστάζουμε να ρωτήσουμε: μπορούν αυτά τα λεφτά να δαπανηθούν για τη βελτίωση της ζωής στην περιοχή του Βόλογκοντσκ; Επειδή η περιοχή μας έχει μεγάλο χρέος, δεν έχουμε λεφτά για τίποτα.",[ヴォログダ州は多くの負債を抱えているため、まったくお金がないのです。 ここには、橋や道路、スポーツや商業開発、雇用機会の創出などが必要です。]

Language: fas (Farsi)

,source,target
726,@NadiaE: Τι ωραίο να ξυπνάς το πρωί ακούγοντας για την νίκη #Obama.,[@NadiaE:خیلی خوب بود امروز صبح با خبر پیروزی اوباما بیدار شدن.]

## Task: Intent Classification

In [ ]:
rizou = gena.RizouDt(datasets=gr_data)
rizou_train = rizou.get('train')
rizou_train.sample()

,ne_tags,text,intent
1678,O O O O teacher_name_b,επικοινωνια με την καθηγητρια δασυρα,getTeacherInfoByTeacherName

## Task: Named Entity Recognition

In [ ]:
ner = gena.BarziokasDt(datasets=gr_data)
ner_train = ner.get('test')
ner_train.sample()

Download github items in directory: /content/repo_285
Successfully downloaded dataset

,sentence,ne_tag4,ne_tag18
19891,"[Σαν, σήμερα, στις, 20, Ιουλίου, 1973, ,, έφυγε, από, τη, ζωή, ο, ηθοποιός, ,, συγγραφέας, ,, θρύλος, των, πολεμικών, τεχνών, και, λαϊκό, είδωλο, ,, Μπρους, Λι.]","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[O, O, O, B-DATE, I-DATE, E-DATE, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]"

## Task: Part of Speech Tagging

In [ ]:
prokopidis_ud = gena.ProkopidisUdDt(datasets=gr_data)
prokopidis_ud_train = prokopidis_ud.get('train')
prokopidis_ud_train.head()

Download github items in directory: /content/repo_438
Successfully downloaded el_gdt-ud-train.conllu
Successfully downloaded el_gdt-ud-dev.conllu
Successfully downloaded el_gdt-ud-test.conllu

               w            l     x     p  g      f Poss Type Gender Aspect  \
s i
1 1            Η            ο   DET   DET  2    det    _  Art    Fem      _
  2   Μάντσεστερ   Μάντσεστερ     X     X  4  nsubj    _    _      _      _
  3  Γιουνάιτεντ  Γιουνάιτεντ     X     X  2   flat    _    _      _      _
  4     ηττήθηκε      ηττώμαι  VERB  VERB  0   root    _    _      _   Perf
  5          από          από   ADP   ADP  7   case    _    _      _      _

    Tense type Mood Person Degree Voice Definite Number Foreign Case
s i
1 1     _  Art    _      _      _     _      Def   Sing       _  Nom
  2     _    _    _      _      _     _        _      _     Yes    _
  3     _    _    _      _      _     _        _      _     Yes    _
  4  Past    _  Ind      3      _  Pass        _   Sing       _    _
  5     _    _    _      _      _     _        _      _       _    _

## Task: Topic Classification

In [ ]:
papaloukas = gena.PapaloukasDt(datasets=gr_data)
papaloukas_train = papaloukas.get('train')
papaloukas_train.sample()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

volume/train-00000-of-00001.parquet:   0%|          | 0.00/87.9M [00:00<?, ?B/s]

volume/test-00000-of-00001.parquet:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

volume/validation-00000-of-00001.parquet:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/28536 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9516 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/9511 [00:00<?, ? examples/s]

chapter/train-00000-of-00001.parquet:   0%|          | 0.00/88.1M [00:00<?, ?B/s]

chapter/test-00000-of-00001.parquet:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

chapter/validation-00000-of-00001.parque(…):   0%|          | 0.00/28.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/28536 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9516 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/9511 [00:00<?, ? examples/s]

subject/train-00000-of-00001.parquet:   0%|          | 0.00/88.9M [00:00<?, ?B/s]

subject/test-00000-of-00001.parquet:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

subject/validation-00000-of-00001.parque(…):   0%|          | 0.00/29.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/28536 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9516 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/9511 [00:00<?, ? examples/s]

,text,volume,chapter,subject
14991,"32. ΑΠΟΦΑΣΗ ΥΠΟΥΡΓΟΥ ΓΕΩΡΓΙΑΣ Αριθ. 273335 της 11/19 Μαΐου 1981 (ΦΕΚ Β΄ 283) Περί καθορισμού αυξημένων ημερομισθίων εποχιακού προσωπικού δακοκτονίας. Έχοντας υπόψη: 1.Τις διατάξεις του Νόμ. 400/76 «περί Υπουργικού Συμβουλίου και Υπουργείων». 2.Τις διατάξεις της παρ. 1 του άρθρ. 5 του Ν.Δ. 1198/1972 και των παρ. 2 και 3 του άρθρ. 10 του Νόμ. 435/76. 3.Την παρ. 1 και 2 του διατακτικού της 17377/ 3688//28.6.78 (ΦΕΚ 581/30.6.78 τ.Β΄) κοινής αποφάσεως των Υπουργών Προεδρίας Κυβερνήσεως, Οικονομικών, Γεωργίας και Εργασίας. 4.Την 31916/6919/5.8.78 (ΦΕΚ 658/7.8.78 τ.Β΄) κοινή υπουργική απόφαση. 5.Τη 12363/16.6.80 (ΦΕΚ 568/25.6.80 τ.Β΄) κοινή υπουργική απόφαση, σε συνδυασμό με τη 10393/6.2.81 (ΦΕΚ 96/13.2.81 τ.Β΄) όμοια. 6.Τη σχετική πρόταση της Δ/νσεως Προστασίας Φυτών, για τον καθορισμό αυξημένων ημερομισθίων, στο εκτάκτως προσλαμβανόμενο προσωπικό, που θα απασχολείται από το Ταμείο Προστασίας Ελαιοπαραγωγής της Χώρας κατά την τρέχουσα Ελαιοκομική περίοδο, για την καταπολέμηση του δάκου της ελιάς, αποφασίζουμε: Στο εκτάκτως προσλαμβανόμενο προσωπικό, σύμφωνα με τις διατάξεις του Ν.Δ. 2413/1953, για την εκτέλεση των εργασιών καταπολεμήσεως του δάκου της ελιάς σε περιοχές της τοπικής αρμοδιότητας των Ταμείων Προστασίας Ελαιοπαραγωγής της Χώρας, εγκρίνουμε την καταβολή αυξημένων ημερομισθίων από της ενάρξεως της διανυομένης ελαιοκομικής περιόδου 1981 και με τους όρους και περιορισμούς των παρ. 2 και 3 του διατακτικού της 17377/3688/28.6.1978 κοινής υπουργικής αποφάσεως, καθώς και της παρ. 1 του διατακτικού της 31916/6919/5.8.78 κοινής αποφάσεώς μας και του Υπουργού Εργασίας το ύψος των οποίων καθορίζουμε κατ’ ειδικότητας μισθωτών, ως κατωτέρω: από δρχ. σε δρχ. α)Τομεάρχες Ιδιώτες Γεωπόνοι πτυχιούχοι Μέσων Σχολών β)Τεχνίτες επισκευαστές ψεκαστήρων δακοκτονίας γ)Βοηθοί Τεχνιτών δ)Αρχιεργάτες παρασκευαστές ε)Ψεκαστές και παγιδοθέτες στ)Αποθηκάριοι ζ)Εργάτες Αποθήκης και πειραμάτων η)Βοηθοί παγιδοθέτη και αρχιεργάτη θ)Εργάτες αεροδρομίου και ελικοπτέρου ι)Εργάτες φορτοεκφορτώσεως υλικών δακοκτονίας κ)Μεταφορείς μηχανοκινήτου μέσου λ)Μεταφορείς παγιδοθέτες μ)Οδηγοί ψεκαστικού συγκροτήματος 764 624 538 624 577 627 523 523 624 574 650 600 650 900 900 700 730 700 700 700 650 700 750 800 700 800 ν)Επιμελητές ειδ. εργασιών δακοκτονίας ξ)Δειγματολήπτες ελαιοκάρπου ο)Παγιδοθέτες 523 476,10 600 700 600 700",1,232,1911